version: 1.2

phases:
  install:
    runtime-versions:
      java: corretto17 
  build:
    commands:
      - echo Packaging JAR File...
      - mvn clean package
  post_build:
    commands:
      - echo build done.
  artifacts:
    files:
      - target/weather-app.jar
    discard-paths: yes